"""Noise residual: what is left of the luma after a median filter takes the scene away.

A photograph's noise is close to uniform across the frame, because it comes
from one sensor at one ISO. Anything that arrived by another route -- a region
pasted from a different photograph, a patch generated by a model, an area that
was denoised, blurred or upscaled -- carries a different amount of it, and the
seam between the two is often visible as a change in texture rather than a
change in content.

Subtracting a median filter is the cheapest way to see that: the median keeps
edges (unlike a mean) while discarding everything smaller than its window, so
the residual is high-frequency detail plus noise, with the scene mostly
removed. It is the same idea the literature's PRNU and noiseprint work starts
from, without the reference fingerprint either of those needs -- which is why
this is a view and not a signal: it shows the texture, it does not say whose
it is.
"""

from __future__ import annotations

import numpy as np

from imgforensics.core.image import ForensicImage
from imgforensics.core.parameters import ParameterSpec
from imgforensics.core.registry import register
from imgforensics.core.types import DetectionResult
from imgforensics.views.base import ViewTool, luma, neighbourhood, normalize_by_p99

DEFAULT_WINDOW = "3"

#: Median window sizes offered, as the strings a choice parameter carries.
#: A 5x5 window costs 25 stacked copies of the luma plane and removes more of
#: the scene; anything wider stops being a local median in any useful sense.
WINDOWS: tuple[str, ...] = ("3", "5")


def median_filter(plane: np.ndarray, window: int) -> np.ndarray:
    """The ``window`` x ``window`` median of a 2-D plane, at the plane's own shape.

    Implemented as a partition over the stacked neighbourhood
    (:func:`~imgforensics.views.base.neighbourhood`) rather than a sort or a
    SciPy call: for an odd window the middle order statistic is exactly the
    median, and partitioning stops as soon as it is in place.
    """
    stack = neighbourhood(plane, window // 2)
    middle = stack.shape[0] // 2
    return np.partition(stack, middle, axis=0)[middle]


def noise_residual_map(plane: np.ndarray, window: int = 3) -> np.ndarray:
    """The view's map: absolute median residual of the luma, scaled by its own p99."""
    return normalize_by_p99(np.abs(plane - median_filter(plane, window)))[0]


@register("noise_residual")
class NoiseResidualView(ViewTool):
    """Absolute difference between the luma and its local median, scaled by its p99.

    Bright means high-frequency detail or noise; dark means a locally smooth
    area. Read it for regions whose noise level differs from their
    surroundings -- a suspiciously clean patch inside a noisy frame, or a
    rectangle of texture that stops at its own border. Every recompression
    and every resize rewrites this map, so a laundered image says little.
    """

    name = "noise_residual"

    def __init__(self, window: str = DEFAULT_WINDOW) -> None:
        self.window = window

    @classmethod
    def parameters(cls) -> list[ParameterSpec]:
        return [
            ParameterSpec(
                name="window",
                kind="choice",
                default=DEFAULT_WINDOW,
                choices=list(WINDOWS),
                description=(
                    "Side of the median window. 3 keeps the finest texture; 5 removes more "
                    "of the scene, leaving a residual that is closer to noise alone."
                ),
            )
        ]

    def predict(self, image: ForensicImage) -> DetectionResult:
        plane = luma(image.rgb)
        window = int(self.window)
        heatmap, p99 = normalize_by_p99(np.abs(plane - median_filter(plane, window)))
        return self.view_result(
            heatmap,
            window=window,
            p99=p99,
            mean=float(heatmap.mean()),
        )
